name: Fetch Exchange Rates

permissions:
    contents: read
    actions: read

on:
    schedule:
        -   cron: "0 18 * * *"
    
    workflow_dispatch:

jobs:
    trigger-main:
        runs-on: ubuntu-latest   
        
        steps:
            -   name: Trigger main.yml
                uses: peter-evans/repository-dispatch@v3.0.0
                with:
                   token: ${{ secrets.REPO_PAT }}
                   event-type: fetch-exchange-rates
