name: Fetch Exchange Rates

on:
    schedule:
        -   cron: "0 18 * * *"
    
    workflow_dispatch:

jobs:
    trigger-main:
        runs-on: ubuntu-latest

         permissions:
            contents: read
            repository_dispatch: write
        
        steps:
            -   name: Trigger main.yml
                uses: peter-evans/repository-dispatch@v3.0.0
                with:
                   event-type: fetch-exchange-rates
